/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as StudentRouteImport } from './routes/student'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ParentRouteImport } from './routes/parent'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeacherIndexRouteImport } from './routes/teacher.index'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as ParentIndexRouteImport } from './routes/parent.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AccountsIndexRouteImport } from './routes/accounts.index'
import { Route as TeacherInsightsRouteImport } from './routes/teacher.insights'
import { Route as TeacherAttendanceRouteImport } from './routes/teacher.attendance'
import { Route as TeacherAssignmentsRouteImport } from './routes/teacher.assignments'
import { Route as StudentSubjectsRouteImport } from './routes/student.subjects'
import { Route as StudentAttendanceRouteImport } from './routes/student.attendance'
import { Route as StudentAssignmentsRouteImport } from './routes/student.assignments'
import { Route as ProfileWorkspaceRouteImport } from './routes/profile.workspace'
import { Route as ProfilePreferencesRouteImport } from './routes/profile.preferences'
import { Route as ProfileActivityRouteImport } from './routes/profile.activity'
import { Route as ProfileAccountRouteImport } from './routes/profile.account'
import { Route as ParentNotificationsRouteImport } from './routes/parent.notifications'
import { Route as ParentAttendanceRouteImport } from './routes/parent.attendance'
import { Route as AdminUploadsRouteImport } from './routes/admin.uploads'
import { Route as AdminTimetableRouteImport } from './routes/admin.timetable'
import { Route as AdminStudentsRouteImport } from './routes/admin.students'
import { Route as AdminStaffRouteImport } from './routes/admin.staff'
import { Route as AccountsTransactionsRouteImport } from './routes/accounts.transactions'

const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentRoute = ParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeacherRoute,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const ParentIndexRoute = ParentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ParentRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AccountsIndexRoute = AccountsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountsRoute,
} as any)
const TeacherInsightsRoute = TeacherInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherAttendanceRoute = TeacherAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherAssignmentsRoute = TeacherAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => TeacherRoute,
} as any)
const StudentSubjectsRoute = StudentSubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => StudentRoute,
} as any)
const StudentAttendanceRoute = StudentAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => StudentRoute,
} as any)
const StudentAssignmentsRoute = StudentAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => StudentRoute,
} as any)
const ProfileWorkspaceRoute = ProfileWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfilePreferencesRoute = ProfilePreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileActivityRoute = ProfileActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileAccountRoute = ProfileAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => ProfileRoute,
} as any)
const ParentNotificationsRoute = ParentNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => ParentRoute,
} as any)
const ParentAttendanceRoute = ParentAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => ParentRoute,
} as any)
const AdminUploadsRoute = AdminUploadsRouteImport.update({
  id: '/uploads',
  path: '/uploads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTimetableRoute = AdminTimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminRoute,
} as any)
const AccountsTransactionsRoute = AccountsTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AccountsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/assistant': typeof AssistantRoute
  '/parent': typeof ParentRouteWithChildren
  '/profile': typeof ProfileRouteWithChildren
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/accounts/transactions': typeof AccountsTransactionsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/timetable': typeof AdminTimetableRoute
  '/admin/uploads': typeof AdminUploadsRoute
  '/parent/attendance': typeof ParentAttendanceRoute
  '/parent/notifications': typeof ParentNotificationsRoute
  '/profile/account': typeof ProfileAccountRoute
  '/profile/activity': typeof ProfileActivityRoute
  '/profile/preferences': typeof ProfilePreferencesRoute
  '/profile/workspace': typeof ProfileWorkspaceRoute
  '/student/assignments': typeof StudentAssignmentsRoute
  '/student/attendance': typeof StudentAttendanceRoute
  '/student/subjects': typeof StudentSubjectsRoute
  '/teacher/assignments': typeof TeacherAssignmentsRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
  '/teacher/insights': typeof TeacherInsightsRoute
  '/accounts/': typeof AccountsIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/parent/': typeof ParentIndexRoute
  '/student/': typeof StudentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/profile': typeof ProfileRouteWithChildren
  '/accounts/transactions': typeof AccountsTransactionsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/timetable': typeof AdminTimetableRoute
  '/admin/uploads': typeof AdminUploadsRoute
  '/parent/attendance': typeof ParentAttendanceRoute
  '/parent/notifications': typeof ParentNotificationsRoute
  '/profile/account': typeof ProfileAccountRoute
  '/profile/activity': typeof ProfileActivityRoute
  '/profile/preferences': typeof ProfilePreferencesRoute
  '/profile/workspace': typeof ProfileWorkspaceRoute
  '/student/assignments': typeof StudentAssignmentsRoute
  '/student/attendance': typeof StudentAttendanceRoute
  '/student/subjects': typeof StudentSubjectsRoute
  '/teacher/assignments': typeof TeacherAssignmentsRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
  '/teacher/insights': typeof TeacherInsightsRoute
  '/accounts': typeof AccountsIndexRoute
  '/admin': typeof AdminIndexRoute
  '/parent': typeof ParentIndexRoute
  '/student': typeof StudentIndexRoute
  '/teacher': typeof TeacherIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/assistant': typeof AssistantRoute
  '/parent': typeof ParentRouteWithChildren
  '/profile': typeof ProfileRouteWithChildren
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/accounts/transactions': typeof AccountsTransactionsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/timetable': typeof AdminTimetableRoute
  '/admin/uploads': typeof AdminUploadsRoute
  '/parent/attendance': typeof ParentAttendanceRoute
  '/parent/notifications': typeof ParentNotificationsRoute
  '/profile/account': typeof ProfileAccountRoute
  '/profile/activity': typeof ProfileActivityRoute
  '/profile/preferences': typeof ProfilePreferencesRoute
  '/profile/workspace': typeof ProfileWorkspaceRoute
  '/student/assignments': typeof StudentAssignmentsRoute
  '/student/attendance': typeof StudentAttendanceRoute
  '/student/subjects': typeof StudentSubjectsRoute
  '/teacher/assignments': typeof TeacherAssignmentsRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
  '/teacher/insights': typeof TeacherInsightsRoute
  '/accounts/': typeof AccountsIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/parent/': typeof ParentIndexRoute
  '/student/': typeof StudentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/admin'
    | '/assistant'
    | '/parent'
    | '/profile'
    | '/student'
    | '/teacher'
    | '/accounts/transactions'
    | '/admin/staff'
    | '/admin/students'
    | '/admin/timetable'
    | '/admin/uploads'
    | '/parent/attendance'
    | '/parent/notifications'
    | '/profile/account'
    | '/profile/activity'
    | '/profile/preferences'
    | '/profile/workspace'
    | '/student/assignments'
    | '/student/attendance'
    | '/student/subjects'
    | '/teacher/assignments'
    | '/teacher/attendance'
    | '/teacher/insights'
    | '/accounts/'
    | '/admin/'
    | '/parent/'
    | '/student/'
    | '/teacher/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/profile'
    | '/accounts/transactions'
    | '/admin/staff'
    | '/admin/students'
    | '/admin/timetable'
    | '/admin/uploads'
    | '/parent/attendance'
    | '/parent/notifications'
    | '/profile/account'
    | '/profile/activity'
    | '/profile/preferences'
    | '/profile/workspace'
    | '/student/assignments'
    | '/student/attendance'
    | '/student/subjects'
    | '/teacher/assignments'
    | '/teacher/attendance'
    | '/teacher/insights'
    | '/accounts'
    | '/admin'
    | '/parent'
    | '/student'
    | '/teacher'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/admin'
    | '/assistant'
    | '/parent'
    | '/profile'
    | '/student'
    | '/teacher'
    | '/accounts/transactions'
    | '/admin/staff'
    | '/admin/students'
    | '/admin/timetable'
    | '/admin/uploads'
    | '/parent/attendance'
    | '/parent/notifications'
    | '/profile/account'
    | '/profile/activity'
    | '/profile/preferences'
    | '/profile/workspace'
    | '/student/assignments'
    | '/student/attendance'
    | '/student/subjects'
    | '/teacher/assignments'
    | '/teacher/attendance'
    | '/teacher/insights'
    | '/accounts/'
    | '/admin/'
    | '/parent/'
    | '/student/'
    | '/teacher/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AssistantRoute: typeof AssistantRoute
  ParentRoute: typeof ParentRouteWithChildren
  ProfileRoute: typeof ProfileRouteWithChildren
  StudentRoute: typeof StudentRouteWithChildren
  TeacherRoute: typeof TeacherRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent': {
      id: '/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof ParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/'
      fullPath: '/teacher/'
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/parent/': {
      id: '/parent/'
      path: '/'
      fullPath: '/parent/'
      preLoaderRoute: typeof ParentIndexRouteImport
      parentRoute: typeof ParentRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/accounts/': {
      id: '/accounts/'
      path: '/'
      fullPath: '/accounts/'
      preLoaderRoute: typeof AccountsIndexRouteImport
      parentRoute: typeof AccountsRoute
    }
    '/teacher/insights': {
      id: '/teacher/insights'
      path: '/insights'
      fullPath: '/teacher/insights'
      preLoaderRoute: typeof TeacherInsightsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/attendance': {
      id: '/teacher/attendance'
      path: '/attendance'
      fullPath: '/teacher/attendance'
      preLoaderRoute: typeof TeacherAttendanceRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/assignments': {
      id: '/teacher/assignments'
      path: '/assignments'
      fullPath: '/teacher/assignments'
      preLoaderRoute: typeof TeacherAssignmentsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/student/subjects': {
      id: '/student/subjects'
      path: '/subjects'
      fullPath: '/student/subjects'
      preLoaderRoute: typeof StudentSubjectsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/attendance': {
      id: '/student/attendance'
      path: '/attendance'
      fullPath: '/student/attendance'
      preLoaderRoute: typeof StudentAttendanceRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/assignments': {
      id: '/student/assignments'
      path: '/assignments'
      fullPath: '/student/assignments'
      preLoaderRoute: typeof StudentAssignmentsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/profile/workspace': {
      id: '/profile/workspace'
      path: '/workspace'
      fullPath: '/profile/workspace'
      preLoaderRoute: typeof ProfileWorkspaceRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/preferences': {
      id: '/profile/preferences'
      path: '/preferences'
      fullPath: '/profile/preferences'
      preLoaderRoute: typeof ProfilePreferencesRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/activity': {
      id: '/profile/activity'
      path: '/activity'
      fullPath: '/profile/activity'
      preLoaderRoute: typeof ProfileActivityRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/account': {
      id: '/profile/account'
      path: '/account'
      fullPath: '/profile/account'
      preLoaderRoute: typeof ProfileAccountRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/parent/notifications': {
      id: '/parent/notifications'
      path: '/notifications'
      fullPath: '/parent/notifications'
      preLoaderRoute: typeof ParentNotificationsRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/attendance': {
      id: '/parent/attendance'
      path: '/attendance'
      fullPath: '/parent/attendance'
      preLoaderRoute: typeof ParentAttendanceRouteImport
      parentRoute: typeof ParentRoute
    }
    '/admin/uploads': {
      id: '/admin/uploads'
      path: '/uploads'
      fullPath: '/admin/uploads'
      preLoaderRoute: typeof AdminUploadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/timetable': {
      id: '/admin/timetable'
      path: '/timetable'
      fullPath: '/admin/timetable'
      preLoaderRoute: typeof AdminTimetableRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/staff': {
      id: '/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof AdminRoute
    }
    '/accounts/transactions': {
      id: '/accounts/transactions'
      path: '/transactions'
      fullPath: '/accounts/transactions'
      preLoaderRoute: typeof AccountsTransactionsRouteImport
      parentRoute: typeof AccountsRoute
    }
  }
}

interface AccountsRouteChildren {
  AccountsTransactionsRoute: typeof AccountsTransactionsRoute
  AccountsIndexRoute: typeof AccountsIndexRoute
}

const AccountsRouteChildren: AccountsRouteChildren = {
  AccountsTransactionsRoute: AccountsTransactionsRoute,
  AccountsIndexRoute: AccountsIndexRoute,
}

const AccountsRouteWithChildren = AccountsRoute._addFileChildren(
  AccountsRouteChildren,
)

interface AdminRouteChildren {
  AdminStaffRoute: typeof AdminStaffRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminTimetableRoute: typeof AdminTimetableRoute
  AdminUploadsRoute: typeof AdminUploadsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminStaffRoute: AdminStaffRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminTimetableRoute: AdminTimetableRoute,
  AdminUploadsRoute: AdminUploadsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ParentRouteChildren {
  ParentAttendanceRoute: typeof ParentAttendanceRoute
  ParentNotificationsRoute: typeof ParentNotificationsRoute
  ParentIndexRoute: typeof ParentIndexRoute
}

const ParentRouteChildren: ParentRouteChildren = {
  ParentAttendanceRoute: ParentAttendanceRoute,
  ParentNotificationsRoute: ParentNotificationsRoute,
  ParentIndexRoute: ParentIndexRoute,
}

const ParentRouteWithChildren =
  ParentRoute._addFileChildren(ParentRouteChildren)

interface ProfileRouteChildren {
  ProfileAccountRoute: typeof ProfileAccountRoute
  ProfileActivityRoute: typeof ProfileActivityRoute
  ProfilePreferencesRoute: typeof ProfilePreferencesRoute
  ProfileWorkspaceRoute: typeof ProfileWorkspaceRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileAccountRoute: ProfileAccountRoute,
  ProfileActivityRoute: ProfileActivityRoute,
  ProfilePreferencesRoute: ProfilePreferencesRoute,
  ProfileWorkspaceRoute: ProfileWorkspaceRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

interface StudentRouteChildren {
  StudentAssignmentsRoute: typeof StudentAssignmentsRoute
  StudentAttendanceRoute: typeof StudentAttendanceRoute
  StudentSubjectsRoute: typeof StudentSubjectsRoute
  StudentIndexRoute: typeof StudentIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentAssignmentsRoute: StudentAssignmentsRoute,
  StudentAttendanceRoute: StudentAttendanceRoute,
  StudentSubjectsRoute: StudentSubjectsRoute,
  StudentIndexRoute: StudentIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

interface TeacherRouteChildren {
  TeacherAssignmentsRoute: typeof TeacherAssignmentsRoute
  TeacherAttendanceRoute: typeof TeacherAttendanceRoute
  TeacherInsightsRoute: typeof TeacherInsightsRoute
  TeacherIndexRoute: typeof TeacherIndexRoute
}

const TeacherRouteChildren: TeacherRouteChildren = {
  TeacherAssignmentsRoute: TeacherAssignmentsRoute,
  TeacherAttendanceRoute: TeacherAttendanceRoute,
  TeacherInsightsRoute: TeacherInsightsRoute,
  TeacherIndexRoute: TeacherIndexRoute,
}

const TeacherRouteWithChildren =
  TeacherRoute._addFileChildren(TeacherRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AssistantRoute: AssistantRoute,
  ParentRoute: ParentRouteWithChildren,
  ProfileRoute: ProfileRouteWithChildren,
  StudentRoute: StudentRouteWithChildren,
  TeacherRoute: TeacherRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
